name: CI/CD Pipeline Just Smile Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Build the Angular application
      - name: Build Angular Application
        run: npm run build -- --prod



  # Additional jobs can be added if needed for testing, linting, etc.
